### ISSUE TITLE
Question about distribution coordinate axis ? 

### ISSUE THREAD

**Issue by Dali936** [yossilevii100/refocusing#2]
![image](https://github.com/user-attachments/assets/44090d24-9b0a-4da9-8620-d0adc6b5ceea)
what's the meaning of x axis and y axis ?

**Comment by yossilevii100** [comment]
This is an histogram of _focus_ measurement over the entire ModelNet-C dataset (clean and corrupted).
Each bin in X axis is implying a range of focus measurement of a point cloud given a classification network, as developed in definition 1 in the paper:
![image](https://github.com/user-attachments/assets/d74380f0-3981-400e-9d5c-f25b25052da0)

So, Y axis is measuring how many samples fell into a certain range of focus.

We can see that addition of points cause the focus to move right, meaning higher, while drop is decreasing the focus. Moreover, our approach (refocusing) is aligning the distribution, causing better performance on corrupted samples even though have'nt seen during training.

**Comment by Dali936** [comment]
> This is an histogram of _focus_ measurement over the entire ModelNet-C dataset (clean and corrupted). Each bin in X axis is implying a range of focus measurement of a point cloud given a classification network, as developed in definition 1 in the paper: ![image](https://private-user-images.githubusercontent.com/94135948/356115705-d74380f0-3981-400e-9d5c-f25b25052da0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzkxMjQsIm5iZiI6MTcyMzE3ODgyNCwicGF0aCI6Ii85NDEzNTk0OC8zNTYxMTU3MDUtZDc0MzgwZjAtMzk4MS00MDBlLTlkNWMtZjI1YjI1MDUyZGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA0NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNjIxZTk1NzMxYzBhYWY2Njc4NWMyODhlZjEyNTYwODUxODdiMjZhYmEzZGFhZDEwZjdmMjFjZTBlNDNjN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._6x7O2mX8_V_eCZYrL5hcT-V-9Zep6JSNhFePxoksZM)
> 
> So, Y axis is measuring how many samples fell into a certain range of focus.
> 
> We can see that addition of points cause the focus to move right, meaning higher, while drop is decreasing the focus. Moreover, our approach (refocusing) is aligning the distribution, causing better performance on corrupted samples even though have'nt seen during training.

so Y axis 'samples'  means points of one object ? or different objects in one corrupted type

**Comment by yossilevii100** [comment]
The Y value measure the number of different point clouds within a certain focus range. The color is coding the corruption type.
For example the peak in the yellow histogram means that there are approx 400 point clouds corrupted by drop global that are with focus of approx 0.1.

**Comment by Dali936** [comment]
> The Y value measure the number of different point clouds within a certain focus range. The color is coding the corruption type. For example the peak in the yellow histogram means that there are approx 400 point clouds corrupted by drop global that are with focus of approx 0.1.

thanks for your clearly reply
