### ISSUE TITLE
Hi,dear author, i am wondering how are you use the parser's parameter of wolfmix  

### ISSUE THREAD

**Issue by Dali936** [yossilevii100/refocusing#3]
![image](https://github.com/user-attachments/assets/4d865b75-0f7d-4d6a-a724-41a79478a09e)
as the title say, i noticed that some parameters in rsmix haven't default setting. Do i need to set them ? and i am curious about what you set this params.Thanks in advance

**Comment by yossilevii100** [comment]
Hi, all the wolfmix relevant args in argparse have the appropeiate default value. Regarding all other extra options (like for example rddrop or jitter), you should not enable them as they are violating the OOD.
I reuse all this part of code from Modelnet-C github page (first link in the acknowlegments).
You can run it without any additional wolfmix flags to the script.

**Comment by Dali936** [comment]
> Hi, all the wolfmix relevant args in argparse have the appropeiate default value. Regarding all other extra options (like for example rddrop or jitter), you should not enable them as they are violating the OOD. I reuse all this part of code from Modelnet-C github page (first link in the acknowlegments). You can run it without any additional wolfmix flags to the script.

thanks for your clearly reply ~
